// eslint-disable-next-line no-shadow
export enum InjectionToken {
  USER_REPOSITORY = 'USER_REPOSITORY',
  USER_USE_CASE = 'USER_USE_CASE',
  LOST_ITEM_REPOSITORY = 'LOST_ITEM_REPOSITORY',
  LOST_ITEM_USE_CASE = 'LOST_ITEM_USE_CASE',
  DRAWER_REPOSITORY = 'DRAWER_REPOSITORY',
  DRAWER_USE_CASE = 'DRAWER_USE_CASE',
  LOCKER_REPOSITORY = 'LOCKER_REPOSITORY',
  LOCKER_PUBLISH_USE_CASE = 'LOCKER_PUBLISH_USE_CASE',
}
